"use client";

import { useEffect, useState } from "react";
import { business, services } from "@/lib/business";

const nav = [["Acasă", "/"], ["Servicii", "/servicii"], ["Despre", "/despre"], ["Recenzii", "/#recenzii"], ["Întrebări", "/#intrebari"], ["Contact", "/contact"]];
const faqs = [
  ["Cât costă serviciile de contabilitate în Sibiu?", "Costul se stabilește în funcție de tipul activității, volumul documentelor, TVA și numărul de angajați. Scrie-ne pe WhatsApp pentru o evaluare potrivită firmei tale."],
  ["Pot schimba contabilul dacă firma mea este deja activă?", "Da. Te ajutăm să facem tranziția organizat, cu documentele și informațiile necesare pentru continuitate."],
  ["Lucrați și cu PFA-uri?", "Da, lucrăm cu PFA-uri, întreprinderi individuale, cabinete și SRL-uri."],
  ["Oferiți servicii de salarizare?", "Da. Pregătim statele de plată, documentele de personal și declarațiile aferente."],
  ["Mă puteți ajuta cu înființarea unui SRL?", "Da. Îți explicăm opțiunile și te ghidăm în pașii de înființare pentru SRL, PFA, II sau ONG."],
  ["Cum transmit documentele contabile?", "Prin canale digitale, într-un mod simplu și stabilit împreună la începutul colaborării."],
  ["Lucrați doar cu firme din Sibiu?", "Suntem aproape de antreprenorii din Sibiu și Șelimbăr, dar putem colabora eficient și digital."],
];

function WhatsApp({ children, className = "", message = "Bună ziua! Aș dori mai multe informații despre serviciile Expert Conta Sibiu." }: { children: React.ReactNode; className?: string; message?: string }) {
  return <a className={`button ${className}`} href={`${business.whatsapp}?text=${encodeURIComponent(message)}`} target="_blank" rel="noreferrer" data-event="whatsapp_click">{children} <span aria-hidden>↗</span></a>;
}

function Header() {
  const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false);
  useEffect(() => { const handler = () => setScrolled(scrollY > 14); addEventListener("scroll", handler); handler(); return () => removeEventListener("scroll", handler); }, []);
  return <header className={`header ${scrolled ? "header-scrolled" : ""}`}><a href="/" className="brand" aria-label="Expert Conta Sibiu - Acasă"><img src={business.logo} alt="Expert Conta Sibiu" /></a><nav className={open ? "nav nav-open" : "nav"} aria-label="Navigare principală">{nav.map(([label, href]) => <a key={label} href={href} onClick={() => setOpen(false)}>{label}</a>)}<WhatsApp className="nav-cta">Discută pe WhatsApp</WhatsApp></nav><button className="menu" onClick={() => setOpen(!open)} aria-label="Deschide meniul" aria-expanded={open}><i></i><i></i></button></header>;
}

function LeadQualifier() {
  const [step, setStep] = useState(0); const [values, setValues] = useState(["", "", "", ""]);
  const questions = [["Ce tip de activitate ai?", ["SRL", "PFA", "ONG", "Altul"]], ["Firma este deja activă?", ["Da", "Nu"]], ["Câți angajați ai?", ["0", "1–5", "6–20", "20+"]], ["De ce serviciu ai nevoie?", ["Contabilitate", "Fiscalitate", "Salarizare", "Înființare firmă", "Altceva"]]];
  const choose = (v: string) => { const n = [...values]; n[step] = v; setValues(n); if (step < 3) setStep(step + 1); };
  const message = `Bună ziua! Am completat formularul de pe site.\n\nTip firmă: ${values[0]}\nFirmă activă: ${values[1]}\nAngajați: ${values[2]}\nServiciu: ${values[3]}\n\nAș dori mai multe informații.`;
  return <section className="qualifier" id="evaluare"><div className="qualifier-copy"><p className="eyebrow">EVALUARE RAPIDĂ</p><h2>Spune-ne câteva lucruri despre afacerea ta.</h2><p>În mai puțin de un minut ne oferi contextul necesar pentru o conversație utilă.</p><div className="progress"><span style={{ width: `${(step + 1) * 25}%` }} /></div><small>Pasul {step + 1} din 4</small></div><div className="question-card"><p className="question-number">0{step + 1}</p><h3>{questions[step][0]}</h3><div className="choices">{questions[step][1].map(v => <button key={v} className={values[step] === v ? "choice selected" : "choice"} onClick={() => choose(v)}>{v}<span>→</span></button>)}</div>{step === 3 && values[3] && <WhatsApp message={message} className="continue">Continuă pe WhatsApp</WhatsApp>}</div></section>;
}

function CookieBanner() { const [visible, setVisible] = useState(false); useEffect(() => setVisible(!localStorage.getItem("ecs-cookie")), []); if (!visible) return null; return <aside className="cookies" aria-label="Preferințe cookie"><strong>Preferințele tale contează</strong><p>Folosim cookie-uri necesare pentru funcționarea site-ului. Analiticele opționale rămân oprite până la acord.</p><div><button className="text-button" onClick={() => { localStorage.setItem("ecs-cookie", "necessary"); setVisible(false); }}>Doar necesare</button><button className="dark-button" onClick={() => { localStorage.setItem("ecs-cookie", "accepted"); setVisible(false); }}>Acceptă</button></div></aside> }

export function SitePage() { return <><Header /><main>
  <section className="hero"><div className="hero-copy reveal"><p className="eyebrow">EXPERT CONTABIL CECCAR · SIBIU</p><h1>Contabilitatea firmei tale, <em>în mâini sigure.</em></h1><p className="lead">Mai puțină grijă pentru acte. Mai mult timp pentru afacerea ta.</p><p className="intro">Servicii complete de contabilitate, fiscalitate și salarizare pentru antreprenori și companii din Sibiu. Soluții clare, comunicare directă și peste 11 ani de experiență.</p><div className="hero-actions"><WhatsApp>Discută pe WhatsApp</WhatsApp><a href="#servicii" className="secondary">Vezi serviciile <span>↓</span></a></div><div className="hero-proof"><span><b>{business.years}</b> ani experiență</span><span><b>{business.companies}</b> firme gestionate</span><span><b>CECCAR</b> expert contabil</span></div></div><div className="portrait-wrap reveal"><div className="portrait-orb"></div><img className="portrait" src={business.portrait} alt="Georgiana Nistor, expert contabil CECCAR" /><div className="portrait-card top">✓ Expert contabil<br/><strong>CECCAR</strong></div><div className="portrait-card bottom"><strong>11+ ani</strong><br/>experiență practică</div></div></section>
  <section className="stats" aria-label="Date de referință"><div><b>11+</b><span>ani experiență</span></div><div><b>90+</b><span>firme gestionate</span></div><div><b>CECCAR</b><span>expert contabil</span></div><div><b>SIBIU</b><span>servicii locale</span></div></section>
  <section className="section value"><div className="section-title"><p className="eyebrow">CLARITATE PENTRU ANTREPRENORI</p><h2>Contabilitatea nu ar trebui să îți consume timpul.</h2><p>Ai nevoie de obligații respectate, răspunsuri clare și informații pe care să te poți baza.</p></div><div className="value-grid">{[["01", "Fără stres fiscal", "Respectarea obligațiilor fiscale și informare clară, la timp."], ["02", "Decizii mai bune", "Date financiare explicate într-un limbaj ușor de înțeles."], ["03", "Mai mult timp pentru afacere", "Documente și obligații gestionate fără să te pierzi în detalii."]].map(([n,t,d]) => <article key={n} className="value-card"><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="section services" id="servicii"><div className="section-title split"><div><p className="eyebrow">CE FACEM</p><h2>Servicii complete pentru afacerea ta.</h2></div><p>De la primele documente până la raportare și decizii fiscale, ai un partener care înțelege ritmul unei firme.</p></div><div className="service-grid">{services.map(([t,d], i) => <article className="service-card" key={t}><span>0{i + 1}</span><h3>{t}</h3><p>{d}</p><a href={`/servicii#${t.toLowerCase().replaceAll(" ", "-")}`}>Află mai mult <b>→</b></a></article>)}</div></section>
  <section className="about" id="despre"><div className="about-image"><img src={business.portrait} alt="Georgiana Nistor la Expert Conta Sibiu" /><span>G.N.</span></div><div className="about-copy"><p className="eyebrow">DESPRE GEORGIANA</p><h2>Un partener pentru afacerea ta, nu doar un contabil.</h2><p>La Expert Conta Sibiu primești mai mult decât evidențe și declarații: primești un om care ascultă, explică și rămâne aproape de realitatea afacerii tale.</p><ul><li>Comunicare directă și atenție personală</li><li>Experiență de peste 11 ani</li><li>Calificare Expert Contabil CECCAR</li><li>Înțelegerea provocărilor antreprenoriale</li></ul><p className="signature">Georgiana Nistor</p><WhatsApp>Discută cu Georgiana</WhatsApp></div></section>
  <section className="section process"><div className="section-title centered"><p className="eyebrow">COLABORARE FĂRĂ COMPLICAȚII</p><h2>Începem simplu.</h2></div><div className="timeline">{[["01", "Ne contactezi", "Ne scrii pe WhatsApp și ne spui câteva lucruri despre firma ta."], ["02", "Analizăm situația", "Evaluăm nevoile contabile și fiscale ale afacerii."], ["03", "Stabilim colaborarea", "Primești o soluție adaptată firmei tale."], ["04", "Ne ocupăm de contabilitate", "Tu te concentrezi pe business. Noi ne ocupăm de partea contabilă."]].map(([n,t,d]) => <article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <LeadQualifier />
  <section className="section reviews" id="recenzii"><div className="section-title centered"><p className="eyebrow">RECENZII</p><h2>Ce spun clienții</h2><p>Recenziile reale Google vor fi integrate înainte de lansare.</p></div><div className="review-row">{["Andreea · servicii", "Mihai · construcții", "Irina · cabinet", "Radu · e-commerce", "Elena · PFA", "Dorin · transport"].map(name => <article className="review-card" key={name}><div>★★★★★ <small>DEMO</small></div><p>„Exemplu de testimonial demonstrativ. Componenta este pregătită pentru înlocuirea cu recenzii reale Google.”</p><strong>{name}</strong></article>)}</div></section>
  <section className="industries"><p className="eyebrow">PENTRU AFACERI DIVERSE</p><h2>Lucrăm cu antreprenori din domenii diverse.</h2><div>{["E-commerce", "Servicii", "Cabinete", "Construcții", "HoReCa", "Transport", "Freelanceri", "Consultanță", "Magazine", "Start-up-uri"].map(x => <span key={x}>✦ {x}</span>)}</div></section>
  <section className="section faq" id="intrebari"><div className="section-title split"><div><p className="eyebrow">ÎNTREBĂRI FRECVENTE</p><h2>Răspunsuri clare, de la început.</h2></div><p>Nu găsești răspunsul? Scrie-ne direct pe WhatsApp.</p></div><div className="faq-list">{faqs.map(([q,a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
  <section className="final-cta"><p className="eyebrow">EXPERT CONTA SIBIU</p><h2>Ai nevoie de un contabil pe care te poți baza?</h2><p>Scrie-ne câteva detalii despre afacerea ta și discutăm despre cea mai potrivită soluție.</p><div><WhatsApp>Discută pe WhatsApp</WhatsApp><a className="secondary light" href={business.phoneHref} data-event="phone_click">Sună acum <span>→</span></a></div></section>
  <section className="contact" id="contact"><div><p className="eyebrow">CONTACT</p><h2>Începem cu o conversație.</h2><p>Suntem în Sibiu / Șelimbăr și răspundem cu plăcere întrebărilor tale.</p></div><address><strong>{business.name}</strong><p>{business.address}<br/><small>{business.addressNote}</small></p><a href={business.phoneHref}>{business.phone}</a><a href={`mailto:${business.email}`}>{business.email}</a><p>{business.hours}</p></address><div className="contact-actions"><WhatsApp>Scrie pe WhatsApp</WhatsApp><a className="secondary" href={business.phoneHref}>Sună acum</a></div></section>
</main><footer><div><img src={business.logo} alt="Expert Conta Sibiu"/><p>Servicii profesionale de contabilitate, fiscalitate și salarizare pentru antreprenori și companii din Sibiu.</p></div><div><a href="/servicii">Servicii</a><a href="/despre">Despre</a><a href="/contact">Contact</a><a href="#">Politica de confidențialitate</a></div><small>© 2026 Expert Conta Sibiu. Toate drepturile rezervate.</small></footer><a className="floating-whatsapp" href={business.whatsapp} aria-label="Deschide WhatsApp" target="_blank" rel="noreferrer">◔</a><div className="mobile-actions"><a href={business.phoneHref}>Sună</a><a href={business.whatsapp} target="_blank" rel="noreferrer">WhatsApp</a></div><CookieBanner /></> }
